name: Build and Upload to PyPI

on:
    workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14, macos-15]


    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: Install cibuildwheel and twine
        run: python -m pip install --upgrade cibuildwheel twine

      - name: Build wheels and upload
        run: |
          python -m cibuildwheel --output-dir wheelhouse
          twine upload wheelhouse/* --skip-existing

        env:
          CIBW_BUILD: cp39-* cp310-* cp311-* cp312-* cp313-*  
          CIBW_SKIP: "*-win32 *-manylinux_i686"
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}

